// Normalise source photos in /public/images to WebP (max 2400px wide) and regenerate
// content/image-sizes.ts. Safe to re-run after dropping new JPG/PNG files in: existing
// WebP files are only measured. Logos in /images/site stay PNG to keep transparency.
import sharp from 'sharp';
import { readdir, unlink, writeFile } from 'node:fs/promises';
import path from 'node:path';

const root = 'public/images';
const sizes = {};

for (const dir of await readdir(root)) {
  for (const file of await readdir(path.join(root, dir))) {
    const src = path.join(root, dir, file);
    const keepPng = dir === 'site' && file.endsWith('.png');
    let out = src;

    if (!file.endsWith('.webp') && !keepPng) {
      out = src.replace(/\.(jpe?g|png)$/i, '.webp');
      await sharp(src).rotate().resize({ width: 2400, withoutEnlargement: true }).webp({ quality: 78 }).toFile(out);
      await unlink(src);
    }

    const { width, height } = await sharp(out).metadata();
    sizes[`/images/${dir}/${path.basename(out)}`] = [width, height];
  }
}

const rows = Object.entries(sizes)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([key, [w, h]]) => `  "${key}": { width: ${w}, height: ${h} },`);

await writeFile(
  'content/image-sizes.ts',
  `// Generated by scripts/optimize-images.mjs — intrinsic sizes of everything in /public/images.
export const imageSizes = {
${rows.join('\n')}
} as const satisfies Record<string, { width: number; height: number }>;

export type ImagePath = keyof typeof imageSizes;
`,
);
console.log(`${rows.length} images`);
